### 
POST http://localhost:3000/bookings HTTP/1.1 
content-Type: application/json

{
"userId": 1, "roomId": 1, "startTime": "2024-07-01T10:00:00", "endTime": "2024-07-01T12:00:00"
}

### 
GET http://localhost:3000/rooms HTTP/1.1